core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('verify/', views.verify_code, name='verify'),
    path('resend/', views.resend_code, name='resend'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

#extending the user model
class User(AbstractUser):
    phone = models.TextField(max_length=20, blank=False)
    is_verified = models.BooleanField(default=False)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from users.models import User

class UserCreationForm(BaseUserCreationForm):
    phone = forms.CharField(max_length=20, required=True, help_text='Phone number')

    class Meta:
        model = User
        fields = ('username','phone','password1','password2')


class VerifyForm(forms.Form):
    code = forms.CharField(max_length=8, required=True, help_text='Enter OTP Code')

class ResendCodeForm(forms.Form):
    phone = forms.CharField(max_length=20, required=True, help_text='Insert same Phone number used to register account')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from users.forms import UserCreationForm, VerifyForm, ResendCodeForm
from . import verify
from django.contrib.auth import authenticate, login
from users.decorators import verification_required
from django.contrib import messages

# Create your views here.

@login_required
@verification_required
def index(request):
    return render(request, 'index.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            verify.send(form.cleaned_data.get('phone'))
            return redirect('users:index')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form':form})

@login_required
def verify_code(request):
    if request.method == 'POST':
        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')
            if verify.check(request.user.phone, code):
                request.user.is_verified = True
                request.user.save()
                return redirect('users:index')
    else:

        form = VerifyForm()
    return render(request, 'verify.html', {'form': form})

@login_required
def resend_code(request):
    if request.method == 'POST':
        form = ResendCodeForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data.get('phone')
            if request.user.phone == phone:
                verify.send(phone)
            return redirect('users:verify')
    else:
        form = ResendCodeForm()
    return render(request, 'resend.html', {'form':form})
    

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>OTP AUTH</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:index' %}">Home</a>
              </li>
              
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link position-absolute top-5 start-99 translate-middle" href="#">Hi, {{ request.user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                      </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif %}
              

            </ul>
          </div>
        </div>
      </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

users/templates/index.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>You are verified!</h1>
</div>

{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>Login here</h1>
</div>
<br>
{% for message in messages %}
    
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert"></a>
           {{ message }}
    </div>

{% endfor %}
<br>
<div class="container d-flex align-items-center justify-content-center">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
<br>
<div class="container d-flex align-items-center justify-content-center">
    <p>Don't have an account? <a href="{% url 'users:register' %}">Register</a></p>
</div>

{% endblock %}

users/templates/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container d-flex align-items-center justify-content-center">
    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Logout</button>
    </form>
</div>


{% endblock %}

users/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>Register here</h1>
</div>

<div class="container d-flex align-items-center justify-content-center">
    
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>



{% endblock %}

users/templates/resend.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>Enter phone number to resend code</h1>
</div>
<div class="container d-flex align-items-center justify-content-center">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </form>
</div>

{% endblock %}

users/templates/verify.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<div class="container d-flex align-items-center justify-content-center">
    <h1>Verify your account</h1>
</div>
<div class="container d-flex align-items-center justify-content-center">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Verify</button>
        <a href="{% url 'users:resend' %}"><button type="button" class="btn btn-primary">Resend Code</button></a>

    </form>
</div>

{% endblock %}